name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get -y install poppler-utils
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Generate thumbnail
        run: |
          pdftoppm -png -hide-annotations resume.pdf > resume.png
      - name: Run an Oracle Cloud Infrastructure (OCI) CLI command
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          command: os object put --bucket-name ${{ secrets.OCI_BUCKET }} --file resume.pdf --name MatthewLamResume.pdf --force
      - name: Run an Oracle Cloud Infrastructure (OCI) CLI command
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          command: os object put --bucket-name ${{ secrets.OCI_BUCKET }} --file resume.png --force
