name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get -y install poppler-utils
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Generate thumbnail
        run: |
          pdftoppm -png -hide-annotations resume.pdf > resume.png
      - name: SCP file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "resume.pdf,resume.png"
          target: "/var/www/mryanlam/html"
